# Generated by Django 5.0.4 on 2024-04-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, default=None, max_length=128)),
                ('product_description', models.CharField(blank=True, default=None, max_length=128)),
                ('product_price', models.CharField(blank=True, default=None, max_length=128)),
                ('product_owner', models.CharField(blank=True, default=None, max_length=128)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
